# This is a basic workflow to help you get started with Actions

name: Workflow 

# Controls when the workflow will run s
on:
  schedule:
  - cron:  '00 06 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel# on vérifie si c'est dur
jobs:
  traitement_donnees:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      IDCLIENT: ${{ secrets.IDCLIENT}}
      SECRETCLIENT: ${{ secrets.SECRETCLIENT }}
      CODESECRET: ${{ secrets.CODESECRET }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
        
     # Set-up R
    - name: Install packages
      run: |
        install.packages(c("tidyverse", "rvest"),type="binary")
      shell: Rscript {0}

          
#    # Run R script
    - name: Lance le script de scrap
      run: Rscript descente_pdf.R
        
 # Ajout des fichiers dans le dossier
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add *
        git add data/*
        git commit -am "GH ACTION OK $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
